spring.application.name=movie-booking-system
server.port=${PORT:8082}

spring.datasource.url=jdbc:h2:mem:moviebooking
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false